### ISSUE TITLE
Client lookups

### ISSUE THREAD

**Issue by jomo** [minotar/skin-spec#2]
Are you sure it uses the username and follows the redirect?

----

AFAIK it makes a request to `https://sessionserver.mojang.com/session/minecraft/profile/<uuid>`.
e.g:
`https://sessionserver.mojang.com/session/minecraft/profile/8ce569f21658431f96d4fd4db501505d`
```JSON
{
  "id": "8ce569f21658431f96d4fd4db501505d",
  "name": "connor4312",
  "properties": [
    {
      "name": "textures",
      "value": "eyJ0aW1lc3RhbXAiOjE0MjAyMzk1NjUxNTQsInByb2ZpbGVJZCI6IjhjZTU2OWYyMTY1ODQzMWY5NmQ0ZmQ0ZGI1MDE1MDVkIiwicHJvZmlsZU5hbWUiOiJjb25ub3I0MzEyIiwidGV4dHVyZXMiOnsiU0tJTiI6eyJ1cmwiOiJodHRwOi8vdGV4dHVyZXMubWluZWNyYWZ0Lm5ldC90ZXh0dXJlL2U3NzQ1NWI5ZjEzNzc4ZjI1NGNjOGYzYTUyYTNjZWQ0NGI4ZTk0OTFkMzEzYjEzOGRlOWVkNWE4NzgwNzIifX19"
    }
  ]
}
```

The `textures` property is Base64 encoded JSON (I guess that's what they store in their DB). When decoded, it looks like this:
```JSON
{
  "timestamp": 1420239565154,
  "profileId": "8ce569f21658431f96d4fd4db501505d",
  "profileName": "connor4312",
  "textures": {
    "SKIN": {
      "url": "http://textures.minecraft.net/texture/e77455b9f13778f254cc8f3a52a3ced44b8e9491d313b138de9ed5a878072"
    }
  }
}
```

the `textures` object can have a `SKIN` and/or `CAPE` object. I haven't seen any other keys than `url` here.

**Comment by LukeHandle** [comment]
Yea, judging by what @lukegb has done over in https://github.com/minotar/minecraft/pull/14 I would say you are probably right. If you make a PR I would be happy to merge it in ;)
