### ISSUE TITLE
rate limited = Steve?

### ISSUE THREAD

**Issue by jomo** [minotar/skin-spec#4]
> the response for being rate limited is the default Steve skin.

this doesn't seem to be right.
I just tried

``` fish
while true
    curl -sSL -o /dev/null -w "%{url_effective} %{http_code} %{time_total}s\\n" "http://skins.minecraft.net/MinecraftSkins/Notch.png" &
end
```

and never ran into any sort of rate limits nor did it redirect to a steve skin.

**Comment by LukeHandle** [comment]
This was based upon @clone1018's findings when battling with trying to keep minotar.net returning valid skins and not Steve skins.

There was possibly other factors at play, but based upon what was seen, I have been under the impression is was a rate limit at some point.

**Comment by connor4312** [comment]
Try getting a random URL. As with Minotar, there's likely a CDN running in front of their application server preventing you from being rate limited when you repeatedly request a single skin.

**Comment by jomo** [comment]
Just tried the same with `http://skins.minecraft.net/MinecraftSkins/$RANDOM.png` but still no steves
